package org.tpl.business.model.fantasy;

public enum FormationPosition {
    GOALKEEPER,
    DEFENDER1,DEFENDER2,DEFENDER3,DEFENDER4,DEFENDER5,
    MIDFIELDER1,MIDFIELDER2,MIDFIELDER3,MIDFIELDER4,MIDFIELDER5,
    STRIKER1,STRIKER2,STRIKER3,STRIKER4;
}
